(defun cilindro ()
    (print "Dame el radio del cilindro: ")
    (setq r(read))
    (print "Dame la altura del cilindro: ")
    (setq h(read))
    (let ((pi 3.14159265359)))
    (setq resultado((* pi (* r r) h)))
          (write resultado)
)