(defun romboide ()
  (print "Dame la longitud de la base mayor del romboide: ")
  (setq bmayor (read))
  (print "Dame la longitud de la base menor del romboide: ")
  (setq bmenor (read))
  (print "Dame la altura del romboide: ")
  (setq h (read))
  (setq resultado (* bmayor bmenor h))
  (write resultado)
)
