(defun PrismaRectangular()
    (print "Dame el ancho del prisma: ")
    (setq a (read))
    (print "Dame la base del prisma: ")
    (setq b (read))
    (print "Dame la altura del prisma: ")
    (setq h (read))
    (setq resultado (* a b h))
     (write resultado)
)