(defun troncodecono ()
(print "Dame la altura del tronco de cono: ")
(setq altura (read))
(print "Dame el radio mayor del tronco de cono: ")
(setq rMayor (read))
(print "Dame el radio menor del tronco de cono: ")
(setq rMenor (read))
(setq resultado (/ (* 3.14 altura (+ (* rMayor rMayor) (* rMayor rMenor) (* rMenor rMenor))) 3))
(write resultado)
)